explicitConnectiveRelationDict={
    'accordingly':{'result':5},
    'additionally':{'Conjunction':7},
    'after':{'expectation':2,'expectation/succession':1,'reason/succession':50,'specification/succession':1,'succession':523},
    'afterward':{'precedence':11},
    'also':{'Conjunction':1733,'Conjunction/Synchrony':2, 'List':10, 'specification':1},
    'alternatively':{'Alternative':2,'disjunctive':4},
    'although':{'COMPARISON':16,'Concession':1, 'contra-expectation':21, 'Contrast':114, 'Exception':1, 'expectation':132, 'juxtaposition':34,'opposition':9},
    'and':{'Conjunction':2543, 'Conjunction/Contrast':1, 'Conjunction/general':1, 'Conjunction/juxtaposition':5, 'Conjunction/opposition':1, 'Conjunction/precedence':30, 'Conjunction/result': 138, 'Conjunction/Synchrony':4, 'contra-expectation':1,'Contrast':3, 'EXPANSION':1, 'generalization':1, 'hypothetical':1, 'hypothetical/precedence':1, 'Instantiation':1, 'juxtaposition':11, 'juxtaposition/List':1, 'List':210, 'opposition':5, 'precedence':1, 'precedence/result':1, 'result':38, 'specification':1},
    'as':{'COMPARISON/Synchrony':2, 'Conjunction':1, 'CONTINGENCY/Synchrony':1, 'contra-expectation':1, 'EXPANSION':1, 'expectation':2, 'justification':1, 'justification/Synchrony':2, 'opposition':1, 'reason':166, 'reason/succession':23, 'reason/Synchrony':144, 'reason/TEMPORAL':1, 'result/Synchrony':2, 'succession':3, 'Synchrony':387},
    'as a result':{'result':78},
    'as an alternative':{'disjunctive':2},
    'as if':{'contra-expectation':4, 'EXPANSION':11, 'Pragmatic_Concession':1},
    'as long as':{'factual_present/Synchrony':4, 'general':6, 'general/Synchrony':1, 'hypothetical':7, 'hypothetical/Synchrony':2, 'Synchrony':4},
    'as soon as':{'succession':11,'Synchrony':9},
    'as though':{'COMPARISON':3, 'specification':2},
    'as well':{'Conjunction':6},
    'because':{'implicit_assertion':2,'justification':2,'reason':854},
    'before':{'precedence':323, 'succession':3},
    'before and after':{'Asynchronous':1},
    'besides':{'Conjunction':17, 'conjunctive':1, 'juxtaposition':1},
    'but':{'chosen_alternative':2, 'COMPARISON':260, 'COMPARISON/Conjunction':2, 'COMPARISON/precedence':1, 'Concession':2, 'Conjunction':63, 'Conjunction/contra-expectation':1, 'Conjunction/Contrast':1, 'Conjunction/juxtaposition':1, 'Conjunction/Pragmatic_Concession':4, 'Conjunction/Pragmatic_Contrast':14, 'contra-expectation':494, 'contra-expectation/juxtaposition':1, 'Contrast':1609, 'Contrast/precedence':2, 'Exception':2, 'EXPANSION':2, 'EXPANSION/Pragmatic_Contrast':1, 'expectation':12, 'juxtaposition':636, 'juxtaposition/List':1, 'opposition':174, 'opposition/precedence':1, 'opposition/reason':1, 'Pragmatic_Concession':4, 'Pragmatic_Contrast':14, 'Pragmatic_Contrast/specification':1, 'result':1, 'specification':1},
    'by comparison':{'COMPARISON':1, 'Contrast':3, 'juxtaposition':7},
    'by contrast':{'Contrast':11, 'juxtaposition':12, 'opposition':4},
    'by then':{'precedence':1, 'precedence/reason':1, 'succession':3, 'Synchrony':2},
    'consequently':{'result':10},
    'conversely':{'Contrast':2},
    'earlier':{'juxtaposition/succession':1, 'succession':14},
    'either':{'Alternative':1, 'conjunctive':1, 'disjunctive':2},
    'else':{'Alternative':1},
    'except':{'disjunctive':1, 'Exception':9},
    'finally':{'Conjunction':11, 'Conjunction/precedence':1, 'EXPANSION/precedence':1, 'List':7, 'precedence':10, 'precedence/result':2},
    'for':{'reason':3},
    'for example':{'Instantiation':194, 'specification':2},
    'for instance':{'Instantiation':98},
    'further':{'Conjunction':9},
    'furthermore':{'Conjunction':11},
    'hence':{'result':4},
    'however':{'COMPARISON':49,'Concession':5, 'Conjunction':2, 'contra-expectation':70,  'Contrast':234, 'expectation':2, 'juxtaposition':89, 'List/opposition':1, 'opposition':31, 'Pragmatic_Concession':1, 'Pragmatic_Contrast':1},
    'if':{'COMPARISON':1, 'Concession':1, 'Condition':2, 'contra-expectation':3, 'contra-expectation/general':1, 'contra-expectation/hypothetical':3, 'Contrast':1, 'expectation':34, 'expectation/factual_present':2, 'expectation/general':1, 'expectation/hypothetical':1, 'factual_past':9, 'factual_present':73, 'factual_present/juxtaposition':1, 'general':175, 'general/Synchrony':1, 'hypothetical':682, 'hypothetical/specification':1, 'implicit_assertion':29, 'juxtaposition':4, 'Pragmatic_Contrast':1, 'relevance':20, 'result':1, 'specification':1, 'unreal_past':53, 'unreal_present': 122},
    'if and when': {'general':1, 'hypothetical':1, 'hypothetical/Synchrony':1},
    'in addition':{'Conjunction':165},
    'in contrast':{'Contrast':5, 'juxtaposition':5, 'opposition':2},
    'in fact':{'COMPARISON':1, 'Conjunction':33, 'Contrast':2, 'EXPANSION':2, 'generalization':1, 'Instantiation':2, 'juxtaposition':3,'Restatement':2, 'specification':36},
    'in other words':{'equivalence':10, 'generalization':3, 'Restatement':4},
    'in particular':{'Instantiation':6, 'specification':9},
    'in short':{'generalization':4},
    'in sum':{'generalization':2},
    'in the end':{'Conjunction':1, 'contra-expectation':1, 'EXPANSION':1, 'generalization':2, 'juxtaposition':1, 'precedence':1, 'result':1, 'specification':1},
    'in turn':{'Asynchronous':1, 'Conjunction':4, 'Conjunction/opposition':1, 'Conjunction/precedence':1, 'Conjunction/Synchrony':1, 'precedence':14, 'precedence/result':4, 'result':3, 'specification':1},
    'indeed':{'COMPARISON':1, 'Conjunction':53, 'Conjunction/result':1, 'equivalence':1, 'EXPANSION':3, 'generalization':1, 'Instantiation':1, 'justification':4, 'Restatement':7,'specification':32},
    'insofar as':{'reason':1},
    'instead':{'Alternative':1, 'Alternative/chosen_alternative':3,'chosen_alternative':105, 'Contrast':2, 'juxtaposition':1},
    'later':{'Conjunction':1, 'precedence':90},
    'lest':{'disjunctive':1,'hypothetical':1},
    'likewise':{'Conjunction':8},
    'meantime':{'Asynchronous':1, 'Conjunction/succession':1, 'Conjunction/Synchrony':1, 'juxtaposition/Synchrony':1,'succession':1,'Synchrony':10},
    'meanwhile':{'Conjunction':25, 'Conjunction/Contrast':2, 'Conjunction/juxtaposition':2, 'Conjunction/Synchrony':92, 'Conjunction/TEMPORAL':1, 'contra-expectation':1, 'Contrast/Synchrony':6, 'Contrast/TEMPORAL':1, 'juxtaposition':9, 'juxtaposition/List':2, 'juxtaposition/Synchrony':15, 'opposition':2, 'opposition/Synchrony':9, 'Synchrony':26},
    'moreover':{'Conjunction':100, 'List':1},
    'much as':{'chosen_alternative':1, 'chosen_alternative/Synchrony':1, 'COMPARISON':1, 'expectation':2, 'specification':1},
    'neither':{'Conjunction':1, 'disjunctive':1, 'opposition':1},
    'nevertheless':{'COMPARISON':1, 'Conjunction/Pragmatic_Concession':1, 'contra-expectation':19, 'Contrast':11, 'juxtaposition':7, 'opposition':1, 'Pragmatic_Concession':4},
    'next':{'Conjunction/precedence':1, 'precedence':6},
    'nonetheless':{'COMPARISON':5, 'Conjunction':1, 'contra-expectation':17, 'Contrast':4},
    'nor':{'Alternative/Conjunction':1, 'Alternative/conjunctive':1, 'Conjunction':25, 'conjunctive':3, 'Contrast':1},
    'now that':{'precedence/reason':1, 'reason':9, 'reason/succession':4, 'reason/Synchrony':4, 'result':2, 'Synchrony':2},
    'on the contrary':{'Contrast':2, 'juxtaposition':1, 'opposition':1},
    'on the one hand':{'Contrast':1},
    'on the other hand':{'COMPARISON':1, 'Conjunction':1, 'Contrast':14, 'juxtaposition':12, 'opposition':9},
    'once':{'general':3, 'general/succession':1, 'hypothetical':1, 'hypothetical/succession':2, 'reason/succession':7, 'result/succession':1, 'succession':67, 'Synchrony':2},
    'or':{'Alternative':32, 'Alternative/conjunctive':2, 'Conjunction':5, 'conjunctive':41, 'Contrast':1, 'disjunctive':12, 'equivalence':1, 'EXPANSION':1, 'implicit_assertion':2, 'Restatement':1},
    'otherwise':{'conjunctive':1, 'disjunctive':21, 'Exception':2},
    'overall':{'Conjunction':3, 'generalization':2, 'Restatement':3, 'specification':4},
    'plus':{'Conjunction':1},
    'previously':{'juxtaposition/succession':3, 'succession':46},
    'rather':{'chosen_alternative':6, 'Contrast':3, 'juxtaposition':1, 'specification':7},
    'regardless':{'contra-expectation':2},
    'separately':{'Alternative/Conjunction':1, 'Conjunction':69, 'Conjunction/Contrast':1, 'Conjunction/Synchrony':2, 'List':1},
    'similarly':{'COMPARISON/Conjunction':2, 'Conjunction':16},
    'simultaneously':{'Synchrony':6},
    'since':{'precedence':1, 'reason':94, 'reason/succession':10, 'succession':78, 'Synchrony':1},
    'so':{'reason':1, 'result':262},
    'so that':{'result':31},
    'specifically':{'Conjunction':1, 'specification':9},
    'still':{'COMPARISON':8, 'Concession':1, 'contra-expectation':80, 'Contrast':68, 'expectation':2, 'juxtaposition':23, 'opposition':5, 'precedence':2, 'Synchrony':1},
    'then':{'Alternative':1, 'COMPARISON':1, 'Conjunction':10, 'Conjunction/precedence': 1, 'Conjunction/result':1, 'contra-expectation':1, 'Contrast':1, 'List':2, 'List/precedence':1, 'precedence':302, 'precedence/reason':1, 'precedence/result':7, 'reason':1, 'result':4, 'Synchrony':5, 'unreal_present':1},
    'thereafter':{'opposition/precedence':1, 'precedence':9, 'succession':1},
    'thereby':{'result':12},
    'therefore':{'result':26},
    'though':{'COMPARISON':12, 'Concession':6, 'contra-expectation':45, 'Contrast':103, 'expectation':105, 'juxtaposition':46, 'opposition':3},
    'thus':{'result':112},
    'till':{'precedence':3},
    'ultimately':{'Conjunction':1, 'Conjunction/precedence':2, 'EXPANSION/precedence':1, 'EXPANSION/succession':1, 'precedence':9, 'precedence/Restatement':1, 'precedence/result':2, 'reason/Restatement':1},
    'unless':{'disjunctive':94, 'hypothetical':1},
    'until':{'disjunctive':3, 'general':2, 'hypothetical':16, 'hypothetical/succession':2, 'precedence':133, 'succession':5, 'Synchrony':1},
    'when':{'CONTINGENCY/succession':1, 'CONTINGENCY/Synchrony':2, 'CONTINGENCY/TEMPORAL':1, 'contra-expectation':1, 'Contrast':1, 'disjunctive':2, 'expectation':8, 'expectation/Synchrony':4, 'factual_present':2, 'factual_present/specification':1, 'factual_present/Synchrony':5, 'general':100, 'general/precedence':1, 'general/specification':1, 'general/succession':9, 'general/Synchrony':50, 'general/TEMPORAL':3, 'hypothetical':11, 'hypothetical/succession':2, 'hypothetical/Synchrony':10, 'implicit_assertion/Synchrony':1, 'justification/succession':1, 'juxtaposition/Synchrony':1, 'opposition':1, 'opposition/Synchrony':1, 'precedence':4, 'reason':6, 'reason/succession':65, 'reason/Synchrony':39, 'reason/TEMPORAL':1, 'relevance/succession':1, 'result/succession':1, 'result/Synchrony':2, 'specification/Synchrony':2, 'succession':157, 'Synchrony':477, 'TEMPORAL':3},
    'when and if':{'hypothetical/succession':1},
    'whereas':{'Contrast':1, 'juxtaposition':3, 'opposition':1},
    'while':{'COMPARISON':18, 'COMPARISON/Synchrony':4, 'Concession':1, 'Conjunction':39, 'Conjunction/Contrast':1, 'Conjunction/juxtaposition':5, 'Conjunction/Synchrony':21, 'Conjunction/TEMPORAL':1, 'contra-expectation':3, 'Contrast':120, 'Contrast/Synchrony':22, 'expectation':79, 'expectation/Synchrony':3, 'juxtaposition':182, 'juxtaposition/List':9, 'juxtaposition/Synchrony':26, 'List':3, 'List/opposition':1, 'opposition':78, 'opposition/Synchrony':11, 'Synchrony':154},
    'yet':{'COMPARISON':12, 'Conjunction':2, 'Conjunction/contra-expectation':2, 'contra-expectation':32, 'Contrast':26, 'juxtaposition':21, 'opposition':6}
}

implicitConnectiveRelationDict={
    'accordingly':{'Conjunction':1, 'result':82, 'result/specification':1, 'specification':1},
    'additionally':{'Conjunction':13},
    'after':{'Conjunction':1, 'reason/succession':9, 'succession':3},
    'afterwards':{'precedence':4},
    'also':{'Conjunction':456, 'Conjunction/result':1, 'conjunctive':1, 'List':2},
    'although':{'COMPARISON':18, 'Concession':4, 'Conjunction':2, 'contra-expectation':24, 'Contrast':100, 'Contrast/Pragmatic_Concession':1, 'Contrast/specification':2, 'EXPANSION/expectation':1, 'expectation':19, 'juxtaposition':27, 'List':1, 'opposition':2, 'specification':1},
    'and':{'Conjunction':891, 'Conjunction/juxtaposition':2, 'Conjunction/precedence':1, 'Conjunction/reason':1, 'Conjunction/Synchrony':1, 'Contrast':1, 'EXPANSION':3, 'Instantiation':1, 'juxtaposition':6, 'juxtaposition/List':7, 'List':346, 'opposition':1, 'precedence':1, 'result':2, 'specification':6, 'succession':1, 'Synchrony':1},
    'as':{'Cause':1, 'Conjunction':11, 'Conjunction/Synchrony':3, 'EXPANSION':1, 'Instantiation/Synchrony':1, 'justification':11, 'justification/specification':3, 'reason':334, 'reason/specification':13, 'reason/Synchrony':3, 'result':1, 'specification':9, 'specification/Synchrony':3, 'Synchrony':17},
    'as a consequence':{'result':2},
    'as a matter of fact':{'Conjunction':1},
    'as a result':{'Conjunction/result':1, 'result':281, 'specification':1},
    'as it turns out':{'Conjunction':1, 'result':1},
    'at that time':{'Synchrony':1},
    'at the same time':{'COMPARISON':1, 'Conjunction':1, 'Conjunction/Synchrony':2, 'Contrast/Synchrony':2, 'Synchrony':4},
    'at the time':{'Conjunction/Synchrony':1, 'Synchrony':21},
    'because':{'Conjunction/reason':2, 'Contrast/reason':1, 'justification':31, 'justification/reason':6, 'List/reason':1, 'reason':1830, 'reason/specification':14, 'specification':2},
    'before':{'succession':5},
    'besides':{'COMPARISON/Conjunction':1, 'Conjunction':14, 'Conjunction/justification':1},
    'but':{'COMPARISON':56, 'COMPARISON/Conjunction':1, 'COMPARISON/reason':1, 'Conjunction':42, 'Conjunction/Pragmatic_Contrast':1, 'conjunctive':1, 'contra-expectation':66, 'Contrast':409, 'Contrast/precedence':1, 'EXPANSION':3, 'expectation':2, 'hypothetical':1, 'juxtaposition':113, 'opposition':39, 'opposition/precedence':1, 'Pragmatic_Contrast':1, 'result':4, 'specification':1},
    'by comparison':{'COMPARISON':1, 'Conjunction':2, 'Conjunction/Contrast':1, 'Conjunction/juxtaposition':1, 'contra-expectation':1, 'Contrast':46, 'EXPANSION':1, 'juxtaposition':137, 'List/opposition':1, 'opposition':7},
    'by contrast':{'Alternative/juxtaposition':1, 'contra-expectation':1, 'Contrast':58, 'juxtaposition':65, 'juxtaposition/precedence':1, 'opposition':20},
    'consequently':{'Conjunction/result':1, 'result':190},
    'earlier':{'succession':28},
    'even though':{'COMPARISON':5, 'Concession':2, 'contra-expectation':7, 'contra-expectation/specification':1, 'Contrast':11, 'expectation':8, 'juxtaposition':2},
    'eventually':{'precedence':3, 'precedence/result':1, 'Restatement':1, 'specification':1},
    'ever since':{'precedence/result':1},
    'finally':{'Conjunction':1, 'juxtaposition/List':1, 'List':1, 'precedence':9, 'Restatement':1, 'result':1},
    'first':{'Conjunction':4, 'Instantiation':1, 'List':8, 'specification':13, 'succession':1},
    'for':{'reason':1},
    'for example':{'Conjunction':1, 'EXPANSION':2, 'Instantiation':733, 'Instantiation/justification':3, 'Instantiation/reason':1, 'reason':1, 'specification':102},
    'for instance':{'Contrast':1, 'Instantiation':581, 'Instantiation/justification':1, 'Instantiation/reason':1, 'List':1, 'specification':43},
    'for one':{'Instantiation':1},
    'for one thing':{'Conjunction':1, 'Instantiation':9, 'Instantiation/justification':1, 'Instantiation/reason':4, 'reason':1, 'reason/specification':2, 'specification':8},
    'further':{'Conjunction':57, 'specification':1},
    'furthermore':{'Conjunction':341, 'CONTINGENCY':1, 'List':1, 'result':1, 'specification':2},
    'hence':{'result':13},
    'however':{'COMPARISON':67, 'Conjunction':13, 'Conjunction/Contrast':1, 'Conjunction/Pragmatic_Contrast':1, 'contra-expectation':61, 'contra-expectation/specification':1, 'Contrast':413, 'Contrast/specification':1, 'EXPANSION':1, 'expectation':1, 'juxtaposition':120, 'opposition':27, 'Pragmatic_Contrast/specification':1, 'specification':1},
    'in addition':{'Conjunction':251, 'List':2, 'specification':1},
    'in comparison':{'juxtaposition':2},
    'in contrast':{'Contrast':8, 'juxtaposition':7, 'opposition':1},
    'in fact':{'Conjunction':436, 'Conjunction/CONTINGENCY':1, 'Conjunction/justification':1, 'Conjunction/juxtaposition':2, 'Conjunction/precedence':1, 'Conjunction/reason':2, 'Conjunction/result':2, 'contra-expectation':1, 'Contrast':2, 'Contrast/Instantiation':1, 'equivalence':5, 'EXPANSION':27, 'generalization':6, 'Instantiation':16, 'justification':7, 'justification/specification':1, 'juxtaposition':4, 'juxtaposition/specification':1, 'List':1, 'reason':2, 'reason/specification':1, 'Restatement':5, 'result':3, 'result/specification':1, 'specification':330},
    'in other words':{'Conjunction':3, 'CONTINGENCY/EXPANSION':1, 'equivalence':169, 'equivalence/reason':1, 'EXPANSION':3, 'generalization':25, 'reason':1, 'Restatement':33, 'result':1, 'specification':15},
    'in particular':{'Conjunction':1, 'Conjunction/juxtaposition':1, 'EXPANSION':2, 'Instantiation':54, 'juxtaposition/specification':1, 'Restatement':1, 'specification':570},
    'in response':{'Conjunction':1},
    'in return':{'Conjunction':1},
    'in short':{'Conjunction':6, 'equivalence':22, 'EXPANSION':7, 'generalization':75, 'reason':2, 'Restatement':22, 'result':1, 'specification':19},
    'in sum':{'Conjunction':6, 'equivalence':4, 'EXPANSION':1, 'generalization':22, 'Restatement':6, 'specification':1},
    'in summary':{'generalization':1},
    'in the end':{'Conjunction':19, 'equivalence':1, 'EXPANSION':8, 'generalization':3, 'precedence':2, 'precedence/result':3, 'Restatement':10, 'result':3, 'specification':4},
    'in the meantime':{'Synchrony':1},
    'in turn':{'Conjunction':9, 'Conjunction/contra-expectation':1, 'Conjunction/opposition':1, 'Conjunction/precedence':3, 'Conjunction/result':3, 'EXPANSION':1, 'precedence':5, 'result':3},
    'inasmuch as': {'justification':4, 'reason':12, 'reason/specification':1},
    'incidentally': {'Conjunction':1},
    'indeed':{'Conjunction':117, 'Conjunction/CONTINGENCY':1, 'Conjunction/justification':2, 'equivalence':37, 'equivalence/reason':1, 'EXPANSION':14, 'EXPANSION/reason':1, 'generalization':22, 'Instantiation':10, 'justification':3, 'reason':3, 'reason/specification':2, 'Restatement':66, 'result':1, 'specification':112},
    'insofar as':{'reason':2, 'reason/specification':1},
    'instead':{'Alternative':1, 'Alternative/chosen_alternative':1, 'chosen_alternative':107, 'Conjunction':1, 'Contrast':28, 'Exception':1, 'juxtaposition':1, 'opposition':1, 'specification':1},
    'later':{'Conjunction/precedence':2, 'precedence':11},
    'likewise':{'Conjunction':18},
    'meanwhile':{'Conjunction':81, 'Conjunction/Contrast':2, 'Conjunction/juxtaposition':6, 'Conjunction/Synchrony':75, 'Conjunction/TEMPORAL':1, 'Contrast':1, 'Contrast/Synchrony':3, 'EXPANSION':3, 'juxtaposition':7, 'juxtaposition/List':5, 'juxtaposition/Synchrony':6, 'List':2, 'List/Synchrony':3, 'precedence':1, 'Synchrony':34},
    'moreover':{'Conjunction':89, 'specification':1},
    'nevertheless':{'Conjunction':1, 'contra-expectation':14, 'Contrast':11, 'juxtaposition':2},
    'next':{'precedence':8},
    'nonetheless':{'contra-expectation':3, 'Contrast':1, 'juxtaposition':3},
    'now':{'precedence':1},
    'on the contrary':{'COMPARISON':1, 'Contrast':6, 'juxtaposition':1, 'opposition':2, 'specification':1},
    'on the one hand':{'Conjunction':1, 'Instantiation':2, 'specification':2},
    'on the other hand':{'COMPARISON':1, 'Contrast':16, 'juxtaposition':15, 'opposition':5},
    'on the whole':{'Conjunction':10, 'EXPANSION':2, 'generalization':18, 'Restatement':12, 'specification':8},
    'or':{'Alternative':1, 'conjunctive':8, 'equivalence':1, 'specification':1},
    'overall':{'Conjunction':11, 'Conjunction/result':1, 'EXPANSION':1, 'generalization':6, 'Restatement':7, 'specification':4},
    'particularly':{'specification':4},
    'plus':{'Conjunction':5, 'Conjunction/reason':1},
    'previously':{'precedence':2, 'succession':110},
    'rather':{'Alternative':1, 'chosen_alternative':63, 'Contrast':29, 'Contrast/EXPANSION':1, 'equivalence':1, 'Exception':1, 'generalization':1, 'juxtaposition':5, 'opposition':3, 'specification':30},
    'regardless':{'Contrast':2},
    'second':{'List':2},
    'separately':{'Conjunction':3},
    'similarly':{'Conjunction':65, 'EXPANSION':1},
    'simultaneously':{'Conjunction/Synchrony':1, 'Synchrony':2},
    'since':{'EXPANSION/justification':1, 'justification':4, 'reason':206, 'specification':2},
    'since then':{'precedence':5},
    'so':{'Conjunction':3, 'Conjunction/result':2, 'generalization':3, 'justification':1, 'precedence/result':2, 'reason':1, 'relevance':1, 'result':787, 'specification':1},
    'so far':{'EXPANSION':1},
    'so that':{'result':2},
    'soon':{'precedence':1},
    'specifically':{'Conjunction':6, 'equivalence':4, 'EXPANSION':1, 'generalization':1, 'Instantiation':24, 'Restatement':1, 'specification':1129},
    'still':{'COMPARISON':1, 'Conjunction/Contrast':1, 'contra-expectation':3, 'Contrast':3, 'juxtaposition':2, 'opposition':2},
    'subsequently':{'EXPANSION':2, 'precedence':43, 'precedence/result':2, 'succession':1},
    'that is':{'Conjunction':2, 'equivalence':28, 'EXPANSION':2, 'generalization':6, 'reason':1, 'Restatement':43, 'result':3, 'specification':34},
    'then':{'Conjunction':3, 'Conjunction/precedence':2, 'List/precedence':2, 'opposition/precedence':1, 'precedence':396, 'precedence/result':4, 'precedence/specification':1, 'result':1, 'result/specification':1, 'specification':3, 'Synchrony':1},
    'thereafter':{'precedence':2},
    'therefore':{'result':113, 'result/specification':1},
    'third':{'List':1},
    'though':{'COMPARISON':1, 'Contrast':3, 'juxtaposition':1},
    'thus':{'justification':1, 'result':176, 'specification':2},
    'to this end':{'result':1},
    'ultimately':{'Conjunction':1, 'Conjunction/precedence':2, 'EXPANSION':1, 'EXPANSION/precedence':1, 'generalization':2, 'precedence':3, 'Restatement':6, 'result':3, 'specification':3},
    "what's more":{'Conjunction':1},
    'when':{'precedence':2, 'specification':1, 'specification/Synchrony':2, 'succession':3, 'Synchrony':10},
    'whereas':{'Conjunction':1, 'Conjunction/Contrast':1, 'Contrast':19, 'juxtaposition':40, 'juxtaposition/List':1, 'juxtaposition/precedence':1, 'opposition':11},
    'while':{'COMPARISON':1, 'Conjunction':336, 'Conjunction/Contrast':2, 'Conjunction/juxtaposition':10, 'Conjunction/opposition':2, 'Conjunction/precedence':3, 'Conjunction/Synchrony':31, 'contra-expectation':1, 'Contrast':44, 'Contrast/TEMPORAL':1, 'EXPANSION':1, 'juxtaposition':118, 'juxtaposition/List':3, 'juxtaposition/precedence':1, 'juxtaposition/Synchrony':12, 'List':6, 'List/Synchrony':2, 'opposition':15, 'opposition/Synchrony':1, 'Synchrony':7},
    'yet':{'COMPARISON':1, 'Conjunction':1, 'contra-expectation':1, 'Contrast':2, 'juxtaposition':1}
    
    

}

## [To Do]
#print(explicitConnectiveRelationDict)
#print(implicitConnectiveRelationDict)

#raise Exception("Check Typos for Discourse Relations")

